import = [
    "~/.config/alacritty/themes/themes/doom_one.toml"
]

shell = "/bin/zsh"

[font]
size = 12.0

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "K", mods = "Alt", action = "ScrollPageUp" },
    { key = "K", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "J", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "Back", mods = "Control|Shift", action = "ResetFontSize" },
    { key = "K", mods = "Alt", action = "ScrollPageUp" },
    { key = "J", mods = "Alt", action = "ScrollPageDown" },
]
