# ~/.config/kitty/kitty.conf
# vim: ft=config

# default xterm colors, dark gray background
foreground #e5e5e5
background #262626
cursor  #ffffff
color0  #000000
color1  #cd0000
color2  #00cd00
color3  #cdcd00
color4  #3a9bdc
color5  #cd00cd
color6  #00cdcd
color7  #e5e5e5
color8  #7f7f7f
color9  #ff0000
color10 #00ff00
color11 #ffff00
color12 #5c5cff
color13 #ff00ff
color14 #00ffff
color15 #ffffff

# General
term xterm-kitty
shell /bin/zsh
shell_integration enabled no-cursor
copy_on_select yes
scrollback_lines 10000
sync_to_monitor yes
enable_audio_bell no
enable_visual_bell no
allow_remote_control socket-only

# Tabs & layouts
tab_bar_style hidden
enabled_layouts stack

# Cursor
cursor_shape block
cursor_blink_interval 0

# Font
font_family family="Hack Nerd Font Mono"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0
disable_ligatures always

# Font size
map ctrl+shift+k change_font_size current +1.0
map ctrl+shift+j change_font_size current -1.0
map ctrl+shift+backspace change_font_size current 0

# URLs
url_color #0087bd
url_style curly
open_url_with default
detect_urls yes

# Disable defaults
map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+enter no_op
map ctrl+shift+r no_op
map ctrl+shift+t no_op
map ctrl+shift+q no_op
map ctrl+shift+space no_op
map ctrl+shift+alt+t no_op
map ctrl+shift+l no_op
map ctrl+shift+equal no_op
map alt+left no_op
map alt+right no_op
map alt+shift+left no_op
map alt+shift+right no_op
map ctrl+t no_op

# Windows
map ctrl+shift+n new_os_window_with_cwd

# URLs & hints
map ctrl+shift+e open_url_with_hints
map ctrl+shift+p>f kitten hints --type path --program -
