# ~/.config/kitty/kitty.conf
# vim: ft=config

# one-dark theme
foreground #979eab
background #282c34
cursor  #e06c75
color0  #282c34
color1  #e06c75
color2  #98c379
color3  #e5c07b
color4  #61afef
color5  #be5046
color6  #56b6c2
color7  #979eab
color8  #393e48
color9  #d19a66
color10 #56b6c2
color11 #e5c07b
color12 #61afef
color13 #be5046
color14 #56b6c2
color15 #abb2bf

# General
term xterm-kitty
shell /bin/zsh
shell_integration enabled no-cursor
copy_on_select yes
scrollback_lines 10000
sync_to_monitor yes
enable_audio_bell no
enable_visual_bell no
allow_remote_control socket-only

# Tabs & layouts
tab_bar_style hidden
enabled_layouts stack

# Cursor
cursor_shape block
cursor_blink_interval 0

# Font
font_family family="Hack Nerd Font Mono"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0
disable_ligatures always

# Font size
map ctrl+shift+k change_font_size current +1.0
map ctrl+shift+j change_font_size current -1.0
map ctrl+shift+backspace change_font_size current 0

# URLs
url_color #0087bd
url_style curly
open_url_with default
detect_urls yes

# Disable defaults
map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+enter no_op
map ctrl+shift+r no_op
map ctrl+shift+t no_op
map ctrl+shift+q no_op
map ctrl+shift+space no_op
map ctrl+shift+alt+t no_op
map ctrl+shift+l no_op
map ctrl+shift+equal no_op
map alt+left no_op
map alt+right no_op
map alt+shift+left no_op
map alt+shift+right no_op
map ctrl+t no_op

# Windows
map ctrl+shift+n new_os_window_with_cwd

# URLs & hints
map ctrl+shift+e open_url_with_hints
map ctrl+shift+p>f kitten hints --type path --program -
