#!/usr/bin/env python

from pathlib import Path
import argparse
import pathlib


class Deployer:
    def __init__(self, home: pathlib.Path):
        self.home = home
        self.config = self.home.joinpath('.config')

        self.dotfiles = [
            ('alacritty', self.config.joinpath('alacritty')),
            ('awesome', self.config.joinpath('awesome')),
            ('bash', self.home),
            ('emacs', self.home.joinpath('.emacs.d')),
            ('i3', self.config.joinpath('i3')),
            ('i3status', self.config.joinpath('i3status')),
            ('neofetch', self.config.joinpath('neofetch')),
            ('nvim', self.config.joinpath('nvim')),
            ('tmux', self.config.joinpath('tmux')),
            ('xmodmap', self.home)
        ]

    def _which_stow() -> bool:
        """
        Check if GNU stow is available in your PATH
        :return: True if stow is installed, otherwise False
        """
        from shutil import which
        return which('stow') is not None

    def _stow(self, name: str, target: pathlib.Path) -> bool:
        """
        Create symlinks for a specific configuration using GNU stow
        :param name: config name
        :param target: path to deploy the config
        """
        import subprocess
        target.mkdir(parents=True, exist_ok=True)
        command = f'stow --dotfiles {name} -t {target}'
        result = subprocess.run(command, shell=True, stdout=subprocess.PIPE)
        return True if result.returncode == 0 else False

    def deploy_config(self, name: str) -> bool:
        """
        Deploy specific configuration files to target
        :param name: configuration name
        """
        try:
            config = list(filter(lambda item: item[0] == name, self.dotfiles))[0]
            target = config[1]
            result = self._stow(name, target)

            if result:
                print(f'[OK] configuration {name} has been deployed successfully.')
                return True

            return False
        except IndexError:
            print(f'[ERR] configuration {name} is not found.')
            return False

    def deploy_all(self) -> None:
        for config_name, _ in self.dotfiles:
            self.deploy_config(config_name)


def get_args() -> argparse.Namespace:
    parser =  argparse.ArgumentParser(description='Deploy configuraiton files')

    parser.add_argument('-d, --deploy',
                        help='deploy configuration files',
                        required=True,
                        action='store_true',
                        dest='deploy')

    parser.add_argument('-r, --remove',
                        help='undeploy configuration file',
                        required=False,
                        action='store_true',
                        dest='undeploy')

    parser.add_argument('-a, --all',
                        help='deploy all configuration files',
                        required=False,
                        action='store_true',
                        dest='deploy_all')

    parser.add_argument('-c, --config',
                        help='configuration name',
                        type=str,
                        required=False,
                        dest='config_name')

    return parser.parse_args()


def main() -> None:
    home = pathlib.Path.home()
    deployer = Deployer(home)

    args = get_args()

    if args.deploy and args.config_name is not None and not args.deploy_all:
        deployer.deploy_config(args.config_name)

    if args.deploy and args.deploy_all and args.config_name is None:
        deployer.deploy_all()


if __name__ == '__main__':
    main()
