#+title: i3 Config
#+author: Ouail Derghal
#+property: header-args :tangle config
#+auto_tangle: t

* General
** Modifiers
*** Mod key
Set the modifier key to be the Windows key on the keyboard. To use the Meta/Alt key instead, modify the =$mod= variable to =Mod1=.

#+begin_src conf
set $mod Mod4
#+end_src

*** Floating modifier
Configure the primary modifier key as the floating modifier for dragging floating windows to their desired positions, and enable window dragging by clicking on the title bar.

#+begin_src conf
floating_modifier $mod
tiling_drag modifier titlebar
#+end_src

*** Vim keys
Define Vim-style keybindings for adjusting window focus, moving windows, and resizing them.

#+begin_src conf
set $up k
set $down j
set $left h
set $right l
#+end_src

** Font family
I prefer to use the patched version of =Ubuntu Mono= font with =Nerd= icons. You can obtain the font from the Nerd Fonts [[https://www.nerdfonts.com/font-downloads][download page]].

#+begin_src conf
font pango:UbuntuMono Nerd Font 10
#+end_src

** Workspaces
Define workspaces variables.

#+begin_src conf
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"
#+end_src

* Startup
** XDG applications
Launch XDG autostart applications, enable =XSS lock= to secure the screen when the computer is in sleep mode, and activate the =NetworkManager applet= to monitor the network status.

#+begin_src conf
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id nm-applet
#+end_src

** Custom applications
The following applications will automatically start when i3 starts up:
|----------------------+-----------------------------------------|
| Command              | Description                             |
|----------------------+-----------------------------------------|
| =nitrogen --restore= | Restore the most recent used wallpaper. |
| =emacs --daemon=     | Launch =emacs= in daemon mode.          |
|----------------------+-----------------------------------------|

#+begin_src conf
exec --no-startup-id nitrogen --restore
exec --no-startup-id emacs --daemon
#+end_src

* Keybindings
** Default mappings
*** Audio
Set keybindings to ajust volume using =pactl= in =PulseAudio=.

#+begin_src conf
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
#+end_src

*** Window managment
Change windows focus (Vim-style and arrow keys):
#+begin_src conf
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
#+end_src

Move focused windows (Vim-style and arrow keys):
#+begin_src conf
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
#+end_src

Split windows in horizontal and vertical directions:
/Note:/ The =$mod+h= binding conflicts with the left Vim-style keybinding.
#+begin_src conf
# bindsym $mod+h split h
bindsym $mod+v split v
#+end_src

Toggle fullscreen mode:
#+begin_src conf
bindsym $mod+f fullscreen toggle
#+end_src

Change container layout (stacked, tabbed, toggle split):
#+begin_src conf
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
#+end_src

Toggle tiling/floating and change focus:
#+begin_src conf
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle
#+end_src

Move the currently focused window to the scratchpad:
#+begin_src conf
bindsym $mod+Shift+minus move scratchpad
#+end_src

Show the next scratchpad window or hide the focused scratchpad window:
#+begin_src conf
bindsym $mod+minus scratchpad show
#+end_src

Cycle through recent workspaces:
#+begin_src conf
bindsym $mod+Tab workspace back_and_forth
#+end_src

*** Workspaces
Switch to a workspace:
#+begin_src conf
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10
#+end_src

Move focused container to workspace:
#+begin_src conf
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10
#+end_src

*** Reload, restart and exit
#+begin_src conf
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
#+end_src

*** Resize mode
#+begin_src conf
mode "resize" {
     bindsym $left       resize shrink width 10 px or 10 ppt
     bindsym $down       resize grow height 10 px or 10 ppt
     bindsym $up         resize shrink height 10 px or 10 ppt
     bindsym $right      resize grow width 10 px or 10 ppt

     bindsym Left        resize shrink width 10 px or 10 ppt
     bindsym Down        resize grow height 10 px or 10 ppt
     bindsym Up          resize shrink height 10 px or 10 ppt
     bindsym Right       resize grow width 10 px or 10 ppt

     bindsym Return mode "default"
     bindsym Escape mode "default"
     bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"
#+end_src


** Custom mappings
#+begin_src conf
bindsym $mod+Shift+d exec xfce4-appfinder
bindsym $mod+b exec google-chrome
bindsym $mod+Shift+b exec google-chrome --incognito
bindsym $mod+Shift+p exec copyq toggle
#+end_src
* Bar
Start i3bar to display a workspace bar:
#+begin_src conf
bar {
    status_command i3status
}
#+end_src
