#!/bin/sh
#
# i3blocks block: memory usage from /proc/meminfo.

total_kb=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
avail_kb=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
used_kb=$((total_kb - avail_kb))

human() {
	awk -v kb="$1" 'BEGIN { printf "%.1f GiB", kb / 1024 / 1024 }'
}

echo "RAM: $(human "$used_kb")/$(human "$total_kb")"
