[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[terminal]
shell.program = "/bin/bash"

[window]
title = "Alacritty"

[scrolling]
history = 10000

[window.padding]
x = 5
y = 5

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Extra Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Back"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
command = { program = "/bin/bash", args = [ "-c", "$HOME/.local/bin/spawn-alacritty-cwd" ] }
key = "N"
mods = "Control|Shift"


[colors.primary]
foreground = '#e3e3e3'
bright_foreground = '#ffffff'
background = '#1f1f1f'


[colors.search]
matches = { foreground = '#b2b2b2', background = '#b26818' }
focused_match = { foreground = "CellBackground", background = "CellForeground" }

[colors.normal]
black   = '#000000'
red     = '#b21818'
green   = '#18b218'
yellow  = '#b26818'
blue    = '#1818b2'
magenta = '#b218b2'
cyan    = '#18b2b2'
white   = '#b2b2b2'

[colors.bright]
black   = '#686868'
red     = '#ff5454'
green   = '#54ff54'
yellow  = '#ffff54'
blue    = '#5454ff'
magenta = '#ff54ff'
cyan    = '#54ffff'
white   = '#ffffff'

[colors.dim]
black   = '#000000'
red     = '#b21818'
green   = '#18b218'
yellow  = '#b26818'
blue    = '#1818b2'
magenta = '#b218b2'
cyan    = '#18b2b2'
white   = '#b2b2b2'

[colors.cursor]
text = '#191622'
cursor = '#b21818'
