# Colors (GruberDarker)

# Default colors
[colors.primary]
background = '#181818'
foreground = '#e4e4ef'

# Normal colors
[colors.normal]
black = '#000000'
red = '#f43841'
green = '#73c936'
yellow = '#ffdd33'
blue = '#96a6c8'
magenta = '#9e95c7'
cyan = '#95a99f'
white = '#ffffff'

# Bright colors
[colors.bright]
black = '#282828'
red = '#ff4f58'
green = '#73c936'
yellow = '#ffdd33'
blue = '#96a6c8'
magenta = '#9e95c7'
cyan = '#95a99f'
white = '#f4f4ff'
