[colors]
  primary = { background = '0x000000', foreground = '0xFFFFFF' }

  [colors.cursor]
  text = '0xFFFFFF'
  cursor = '0xFFFFFF'

  [colors.selection]
  text = '0xFFFFFF'
  background = '0x4D4D4D'

  [colors.normal]
  black = '0x000000'
  red = '0xFF6C6B'
  green = '0x98BE65'
  yellow = '0xECBE7B'
  blue = '0x51AFEF'
  magenta = '0xC678DD'
  cyan = '0x46D9FF'
  white = '0xABB2BF'

  [colors.bright]
  black = '0x5C6370'
  red = '0xE06C75'
  green = '0x98BE65'
  yellow = '0xD19A66'
  blue = '0x61AFEF'
  magenta = '0xC678DD'
  cyan = '0x56B6C2'
  white = '0xFFFFFF'
